### ISSUE TITLE
Spawn animation doesnt fully remove trees in starting location

### ISSUE THREAD

**Issue by Apofenas** [FAForever/nomads#353] opened 2019-01-02 04:01 UTC
Current spawn animation fails to remove tree props. Apparently those are some evergreen trees. (Example Roanoke Abyss).

**Comment by JJ173** [comment] 2019-04-07 18:22
Duplicate of: https://github.com/FAForever/nomads/issues/76

**Closed by JJ173** 2019-04-07 18:22 UTC
