### ISSUE TITLE
T1 Air staging usage is not distributed

### ISSUE THREAD

**Issue by Danthar** [FAForever/nomads#564] opened 2020-07-03 14:45 UTC
Any air unit you build. Will only ever use the very first air staging your make. If you destroy that one they will go to your 2th air staging. But never your 3th / 4th / nth.
Therefore only 1 air staging is only ever used.

This is easily reproducible in any game.

**Comment by Danthar** [comment] 2020-07-03 15:00
To clarify. I build 3 air staging in a row. And my units only ever use the first one build. They ignore the other 2.

**Comment by Exotic-Retard** [comment] 2020-07-03 17:41
cant seem to reproduce this. perhaps you are playing with different mods perhaps that change this behaviour? ![](https://i.imgur.com/gMKCtBf.png)

**Comment by Danthar** [comment] 2020-07-03 18:12
This is wierd. because sofar it has happened every single time. Although i haven't build them spaced out like you did. I build them 3 in a row next to each other. 

Only Mod i have on is increased build range (x1.5 i think).
Ill experiment more consciously with this. And ill update this issue as i find more patterns. Maybe i just keep running into this special case due to my own default patterns of building stuff.

**Comment by Danthar** [comment] 2020-07-03 21:22
I noticed, spacing out the air stagings. Does not cause this issue. Not sure if that is significant or not. Feel free to close if you want.

**Comment by Exotic-Retard** [comment] 2020-07-05 07:55
i think i will close this since cant seem to reproduce it on this end, we can always re-open it now that its got my attention

**Closed by Exotic-Retard** 2020-07-05 07:55 UTC
