### ISSUE TITLE
Assisting mex does not auto-build mass storage. 

### ISSUE THREAD

**Issue by DeiuneRaiLythe** [FAForever/nomads#505] opened 2019-12-22 02:50 UTC
![image](https://user-images.githubusercontent.com/26729641/71316320-6da9d480-2433-11ea-9ff4-99e22c3b5189.png)

Assisting to auto-build mass storage doesn't seem to work for Nomads specifically.

**Comment by Exotic-Retard** [comment] 2019-12-22 09:15
cant confirm ![](https://i.imgur.com/FhvzXtt.png)
tested in both develop and released with and without my ui mods.

please check what ui mods you have enabled, and what version of nomads you are testing with

**Comment by DeiuneRaiLythe** [comment] 2019-12-23 05:41
Turns out this was an issue with SACU's specifically. Normal engineers build just fine.

**Comment by Exotic-Retard** [comment] 2019-12-23 15:20
ah, yep confirmed that one. thanks fam <3

**Comment by speed2CZ** [comment] 2019-12-24 09:03
It's not a bug, it's a feature!

**Comment by Exotic-Retard** [comment] 2019-12-29 18:51
speed2-babe fixed it, so all is well here

**Closed by Exotic-Retard** 2019-12-29 18:51 UTC
